export const MIN_ZOOM = 0.05, MAX_ZOOM = 8;

// Pixel deltas retain the fine movements generated by trackpad pinch gestures.
// Normalize mouse wheel units and limit unusually large individual inputs.
export function wheelZoom(current, deltaY, deltaMode = 0, pageHeight = 800) {
  const scale = Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, current));
  if (!Number.isFinite(deltaY) || deltaY === 0) return scale;
  const page = Number.isFinite(pageHeight) && pageHeight > 0 ? pageHeight : 800;
  const unit = deltaMode === 1 ? 16 : deltaMode === 2 ? page : 1;
  const change = Math.max(-0.06, Math.min(0.06, -deltaY * unit * 0.0012));
  return Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, scale * Math.exp(change)));
}

export const zoomText = scale => `${Number((scale * 100).toFixed(1))}%`;
